# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'DemoScanner' do
  use_frameworks!
  
pod 'SwiftQRScanner', :git => ‘https://github.com/vinodiOS/SwiftQRScanner’

  
end
